Repository caesar-team/caesar-web-client, pull requests merged in 2020-10, with the labels that each got.

#520 Feature/add admin to team by default
  .eslintrc
  packages/common/ability.js
  packages/common/actions/workflow.js
  packages/common/api.js
  packages/common/constants.js
  packages/common/model/item.js
  packages/common/normalizers/normalizers.js
  packages/common/normalizers/schemas/index.js
  packages/common/normalizers/schemas/item.js
  packages/common/normalizers/schemas/keypair.js
  packages/common/normalizers/schemas/keypairItem.js
  packages/common/normalizers/schemas/list.js
  packages/common/normalizers/schemas/team.js
  packages/common/reducers/entities/team.js
  packages/common/reducers/keystore.js
  packages/common/reducers/workflow.js
  packages/common/sagas/common/share.js
  packages/common/sagas/entities/item.js
  packages/common/sagas/entities/team.js
  packages/common/sagas/user.js
  packages/common/sagas/workflow.js
  packages/common/selectors/entities/list.js
  packages/common/selectors/entities/member.js
  packages/common/utils/cipherUtils.js
  packages/common/utils/item.js
  packages/common/workers/decryption.js
  packages/components/AddItem/AddItem.js
  packages/components/CreateForm/CreateForm.js
  packages/components/CreateForm/types/Credentials.js
  packages/components/CreateForm/utils/getInitialValues.js
  packages/components/CreateForm/utils/getValidationSchema.js
  packages/components/Item/Item.js
  packages/components/Item/types/Credentials.js
  packages/components/ItemFields/view/Password.js
  packages/components/List/Item/index.js
  packages/components/MemberList/components/InviteControl.js
  packages/containers/Dashboard/Dashboard.js
  packages/containers/Dashboard/utils.js
  packages/containers/Import/Import.js
  packages/containers/Import/Steps/DataStep/createColumns.js
  packages/containers/Import/Steps/FieldsStep/FieldsStep.js
  packages/containers/Import/Steps/FieldsStep/constants.js
  packages/containers/Import/Steps/FieldsStep/schema.js
  packages/containers/Import/index.js
  packages/containers/Sharing/Sharing.js
  packages/containers/Team/Team.js
  packages/containers/Team/constants.js
  packages/containers/TeamList/TeamList.js
  packages/containers/TeamList/index.js
  packages/extension/components/Item/Types/Credentials/Credentials.js
  packages/web-app/package.json
  yarn.lock
Labels: blocker, important, refactoring

#522 Go to the permissions from the normalizr
  packages/common/normalizers/schemas/item.js
  packages/common/normalizers/schemas/list.js
  packages/components/AddItem/AddItem.js
  packages/components/Item/components/ItemHeader.js
  packages/components/MenuList/components/ListItem.js
  packages/components/MenuList/components/MenuListInner.js
  packages/components/TeamCard/TeamCard.js
  packages/containers/Team/createColumns.js
  packages/containers/TeamList/TeamList.js
Labels: blocker, important, refactoring

#528 Set right permissions and creating an keypair in the refreshed create page
  packages/common/actions/workflow.js
  packages/common/reducers/workflow.js
  packages/common/sagas/entities/item.js
  packages/common/sagas/entities/team.js
  packages/common/sagas/workflow.js
  packages/common/utils/item.js
  packages/components/AddItem/AddItem.js
  packages/components/CreateForm/CreateForm.js
  packages/components/MenuList/components/MenuListInner.js
  packages/containers/Create/Create.js
Labels: blocker, important

#523 Feature/new share api
  .env.dist
  packages/common/ability.js
  packages/common/api.js
  packages/common/constants.js
  packages/common/normalizers/normalizers.js
  packages/common/normalizers/schemas/index.js
  packages/common/normalizers/schemas/item.js
  packages/common/normalizers/schemas/keypair.js
  packages/common/normalizers/schemas/keypairItem.js
  packages/common/normalizers/schemas/list.js
  packages/common/normalizers/schemas/share.js
  packages/common/root/persist.js
  packages/common/root/store.js
  packages/common/sagas/common/share.js
  packages/common/sagas/entities/item.js
  packages/common/sagas/entities/team.js
  packages/common/sagas/workflow.js
  packages/common/selectors/keystore.js
  packages/common/utils/item.js
  packages/components/MenuList/components/ListItem.js
  packages/components/MenuList/components/MenuListInner.js
  packages/containers/Dashboard/components/MiddleColumn.js
  packages/web-app/next.config.js
Labels: blocker, important

#530 Fix the service-worker.js is not found
  packages/web-app/next.config.js
  packages/web-app/server.js
Labels: bugfix, important

#531 Feature/1382 fix teams and users
  packages/common/sagas/entities/team.js
  packages/common/sagas/workflow.js
  packages/common/selectors/entities/team.js
  packages/components/Select/Select.js
  packages/components/SettingsSidebar/SettingsSidebar.js
  packages/components/SettingsWrapper/SettingsWrapper.js
  packages/components/TeamCard/TeamCard.js
  packages/containers/Import/Steps/DataStep/DataStep.js
  packages/containers/Team/Team.js
  packages/containers/TeamList/TeamList.js
  packages/containers/TeamList/index.js
  packages/containers/Users/Users.js
  packages/containers/index.js
Labels: blocker

#533 Fix adding a new member to a team
  packages/common/sagas/entities/team.js
  packages/containers/Team/Team.js
Labels: blocker, bugfix, important

#541 Send the title to the server
  packages/common/sagas/entities/item.js
Labels: blocker, important, improvements

#542 The shared team key contains empty keys
  packages/common/actions/entities/member.js
  packages/common/actions/entities/team.js
  packages/common/normalizers/schemas/team.js
  packages/common/reducers/entities/team.js
  packages/common/sagas/entities/member.js
  packages/common/sagas/entities/team.js
  packages/common/sagas/user.js
  packages/common/sagas/workflow.js
  packages/common/selectors/entities/member.js
  packages/common/selectors/entities/team.js
  packages/common/selectors/keystore.js
  packages/common/selectors/user.js
  packages/components/MenuList/MenuList.js
  packages/components/TeamsList/TeamsList.js
  packages/containers/TeamList/TeamList.js
  packages/secure-app/pages/_app.js
  packages/web-app/pages/_app.js
Labels: blocker, bugfix, important, improvements

#547 Fix sagas order
  packages/common/sagas/workflow.js
Labels: blocker, bugfix, important

#549 Fix getting the team lists
  packages/common/sagas/workflow.js
Labels: blocker, bugfix, important

#548 Feature/caes 1346 fix import
  packages/common/actions/keystore.js
  packages/common/reducers/keystore.js
  packages/common/sagas/entities/item.js
  packages/common/selectors/entities/list.js
  packages/common/selectors/keystore.js
  packages/components/MenuList/MenuList.js
  packages/containers/Import/Steps/DataStep/DataStep.js
  packages/containers/Import/index.js
Labels: blocker

#532 Feature/fix list counter
  packages/common/selectors/entities/item.js
  packages/common/utils/list.js
  packages/components/ItemIcon/ItemIcon.js
  packages/components/ItemIcon/index.js
  packages/components/List/Item/index.js
  packages/components/List/Item/styles.js
  packages/components/List/List.js
  packages/components/MenuList/components/ListItem.js
  packages/components/MenuList/components/MenuListInner.js
  packages/components/index.js
Labels: bugfix, improvements, refactoring

#552 Rename the roles
  packages/common/api.js
  packages/common/constants.js
  packages/common/normalizers/normalizers.js
  packages/common/normalizers/schemas/index.js
  packages/common/normalizers/schemas/member.js
  packages/common/normalizers/schemas/user.js
  packages/common/reducers/entities/member.js
  packages/common/reducers/entities/team.js
  packages/common/sagas/common/anonymous.js
  packages/common/sagas/common/share.js
  packages/common/sagas/entities/member.js
  packages/common/sagas/entities/team.js
  packages/common/sagas/workflow.js
  packages/common/selectors/entities/member.js
  packages/common/selectors/entities/team.js
  packages/common/selectors/user.js
  packages/common/selectors/workflow.js
  packages/containers/Team/Team.js
  packages/containers/Team/constants.js
  packages/containers/Team/createColumns.js
  packages/web-app/pages/settings/team/[id]/index.js
Labels: important, improvements, refactoring

#545 Feature/fix secure app 19.10.20
  packages/components/SecureMessage/SecureMessageLink.js
  packages/secure-app/server.js
Labels: blocker, bugfix

#562 feature/new-keypair-api
  packages/common/api.js
  packages/common/normalizers/normalizers.js
  packages/common/reducers/keystore.js
  packages/common/sagas/common/share.js
  packages/common/sagas/entities/item.js
  packages/common/sagas/entities/team.js
  packages/common/sagas/workflow.js
Labels: important, improvements, refactoring

#567 Refactoring showing avatars and shared items
  packages/common/normalizers/normalizers.js
  packages/common/normalizers/schemas/index.js
  packages/common/normalizers/schemas/invitedUser.js
  packages/common/normalizers/schemas/item.js
  packages/common/sagas/common/share.js
  packages/common/sagas/workflow.js
  packages/components/Item/components/OwnerAndShares.js
  packages/components/Item/types/Document.js
  packages/components/List/Item/index.js
  packages/components/MenuList/components/ListItem.js
Labels: important, refactoring

#576 Fix crash when trying to create an item
  packages/common/reducers/entities/list.js
  packages/common/sagas/entities/item.js
  packages/common/selectors/entities/user.js
Labels: blocker, bugfix, important

#577 Free threads after completed all jobs
  packages/common/sagas/common/decryption.js
  packages/common/sagas/common/job.js
  packages/common/utils/worker.js
Labels: blocker, bugfix, important
